### ISSUE TITLE
Command failed: git config user.name <my user name> fatal: not in a git directory

### ISSUE THREAD

**Issue by StephanMertel** [EndBug/latest-tag#18]
I have the following configuration in my `.github/workflows/create_latest_tag.yml` file:
```
name: Latest Tag
on: push
jobs:
  Create-Latest-Tag:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          # You can change the name of the tag or branch with this input.
          # Default: 'latest'
          ref: latest

          # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
          # Default: ''
          description: We always set the "latest" tag to the last commit in the main branch

          # Force-update a branch instead of using a tag.
          # Default: false
          force-branch: false
```

When pushing a commit to the `main` branch, the action fails with the following error:

```
Run EndBug/latest-tag@latest
  with:
    ref: latest
    description: We always set the "latest" tag to the last commit in the main branch
    force-branch: false
Setting up git user...
Error: Command failed: git config user.name "StephanMertel"
fatal: not in a git directory
```
