### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by HyperCodec** [EndBug/latest-tag#23]
When this workflow runs, I get `Command failed: git push --force origin latest`.

```yaml
name: Add latest tag on release

on: [release]

jobs:
    add-tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: EndBug/latest-tag@latest
              with:
                description: Points to the latest release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by EndBug** [comment]
Hi, can you send me a link to the failing workflow run?

**Comment by HyperCodec** [comment]
> Hi, can you send me a link to the failing workflow run?

https://github.com/HyperCodec/shuttle-deploy/actions/runs/5755302530/job/15602433601

**Comment by HyperCodec** [comment]
appears like it could be an issue related to access for the bot itself

**Comment by EndBug** [comment]
Check the [permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) of your default GitHub token, you might need to explicitly grant `contents: write` to that job

**Comment by HyperCodec** [comment]
> Check the [permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) of your default GitHub token, you might need to explicitly grant `contents: write` to that job

where would i define said permissions?

**Comment by HyperCodec** [comment]
i updated my content to this:
```yaml
name: Add latest tag on release

on: [release, pull_request]

permissions:
    contents: write

jobs:
    add-tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: EndBug/latest-tag@latest
```

but i ended up getting the same error (https://github.com/HyperCodec/shuttle-deploy/actions/runs/5755456695/job/15602911270?pr=7)
